Applied linter in dotfiles

diff --git a/scripts/mac/security_mode b/scripts/mac/security_mode
--- a/scripts/mac/security_mode
+++ b/scripts/mac/security_mode
@@ -89,7 +89,7 @@ security::bonjour_disable() {
 }
 
 ##? Change mac security settings
-##? 
+##?
 ##? See:
 ##?    https://github.com/drduh/macOS-Security-and-Privacy-Guide
 ##?
@@ -129,31 +129,31 @@ sudo -v
 output::empty_line
 
 case "${1:-}" in
-block-on)
-  sudo pfctl -e -f pf.rules &>/dev/null || true
-  exit 0
-  ;;
-block-off)
-  sudo pfctl -d &>/dev/null || true
-  exit 0
-  ;;
-ip-block)
-  [[ -z "${ip_addr:-}" ]] && exit 1
-  sudo pfctl -e -f pf.rules &>/dev/null || true
-  sudo pfctl -t blocklist -T add "$ip_addr"
-  exit 0
-  ;;
-ip-unblock)
-  [[ -z "${ip_addr:-}" ]] && exit 1
-  sudo pfctl -e -f pf.rules &>/dev/null || true
-  sudo pfctl -t blocklist -T delete "$ip_addr"
-  exit 0
-  ;;
-show-block)
-  [[ -z "${ip_addr:-}" ]] && exit 1
-  sudo pfctl -t blocklist -T show
-  exit 0
-  ;;
+  block-on)
+    sudo pfctl -e -f pf.rules &> /dev/null || true
+    exit 0
+    ;;
+  block-off)
+    sudo pfctl -d &> /dev/null || true
+    exit 0
+    ;;
+  ip-block)
+    [[ -z "${ip_addr:-}" ]] && exit 1
+    sudo pfctl -e -f pf.rules &> /dev/null || true
+    sudo pfctl -t blocklist -T add "$ip_addr"
+    exit 0
+    ;;
+  ip-unblock)
+    [[ -z "${ip_addr:-}" ]] && exit 1
+    sudo pfctl -e -f pf.rules &> /dev/null || true
+    sudo pfctl -t blocklist -T delete "$ip_addr"
+    exit 0
+    ;;
+  show-block)
+    [[ -z "${ip_addr:-}" ]] && exit 1
+    sudo pfctl -t blocklist -T show
+    exit 0
+    ;;
 esac
 
 security_modes=(
@@ -170,60 +170,59 @@ if [[ -z "${security_mode:-}" ]]; then
   security_mode="$(printf "%s\n" "${security_modes[@]}" | fzf)"
 fi
 
-[[ -z "$security_mode" ]] &&\
-  ! output::yesno "Sure you want to set a default strict mode" &&\
-  output::error "User aborted" &&\
+[[ -z "$security_mode" ]] &&
+  ! output::yesno "Sure you want to set a default strict mode" &&
+  output::error "User aborted" &&
   exit 1
 
-
 case "${security_mode:-strict}" in
-home)
-  output::answer "Configure File vault"
-  security::file_vault_default &>/dev/null || true
+  home)
+    output::answer "Configure File vault"
+    security::file_vault_default &> /dev/null || true
 
-  output::answer "Configure Firewall"
-  security::firewall_default &>/dev/null || true
+    output::answer "Configure Firewall"
+    security::firewall_default &> /dev/null || true
 
-  output::answer "Disable Screen Saver to ask password"
-  security::screen_passwd_noask &>/dev/null || true
+    output::answer "Disable Screen Saver to ask password"
+    security::screen_passwd_noask &> /dev/null || true
 
-  output::answer "Enabling bonjour"
-  security::bonjour_enable &>/dev/null || true
-  ;;
-website*)
-  open "https://github.com/drduh/macOS-Security-and-Privacy-Guide"
-  ;;
-captive_on)
-  output::answer "Enable captive portal"
-  security::captive_enable &>/dev/null || true
-  ;;
-captive_off)
-  output::answer "Disable captive portal"
-  security::captive_disable &>/dev/null || true
-  ;;
-gatekeeper_on)
-  output::answer "Gatekeeper"
-  {
-    sudo sysctl --master-enable && output::solution "Gatekeeper Enabled"
-  } || output::answer "Gatekeeper could not be enabled"
-  ;;
-gatekeeper_off)
-  output::answer "Gatekeeper"
-  {
-    sudo sysctl --master-disable && output::error "Gatekeeper Disabled"
-  } || output::answer "Gatekeeper could not be disabled"
-  ;;
-*)
-  output::answer "Configure File vault"
-  security::file_vault_strict &>/dev/null || true
-  
-  output::answer "Configure Firewall"
-  security::firewall_strict &>/dev/null || true
-  
-  output::answer "Configure screen saver to ask password"
-  security::screen_passwd_ask &>/dev/null || true
+    output::answer "Enabling bonjour"
+    security::bonjour_enable &> /dev/null || true
+    ;;
+  website*)
+    open "https://github.com/drduh/macOS-Security-and-Privacy-Guide"
+    ;;
+  captive_on)
+    output::answer "Enable captive portal"
+    security::captive_enable &> /dev/null || true
+    ;;
+  captive_off)
+    output::answer "Disable captive portal"
+    security::captive_disable &> /dev/null || true
+    ;;
+  gatekeeper_on)
+    output::answer "Gatekeeper"
+    {
+      sudo sysctl --master-enable && output::solution "Gatekeeper Enabled"
+    } || output::answer "Gatekeeper could not be enabled"
+    ;;
+  gatekeeper_off)
+    output::answer "Gatekeeper"
+    {
+      sudo sysctl --master-disable && output::error "Gatekeeper Disabled"
+    } || output::answer "Gatekeeper could not be disabled"
+    ;;
+  *)
+    output::answer "Configure File vault"
+    security::file_vault_strict &> /dev/null || true
 
-  output::answer "Disable bonjour"
-  security::bonjour_disable &>/dev/null || true
-  ;;
+    output::answer "Configure Firewall"
+    security::firewall_strict &> /dev/null || true
+
+    output::answer "Configure screen saver to ask password"
+    security::screen_passwd_ask &> /dev/null || true
+
+    output::answer "Disable bonjour"
+    security::bonjour_disable &> /dev/null || true
+    ;;
 esac
diff --git a/scripts/secrets/file b/scripts/secrets/file
--- a/scripts/secrets/file
+++ b/scripts/secrets/file
@@ -8,7 +8,7 @@
 # TODO Allow to store secret files in a different path that does not need to be a git repository
 
 ##? Handle stored secrets
-##? 
+##?
 ##?
 ##? Usage:
 ##?   file [-h | --help]
@@ -46,107 +46,107 @@ if ${version:-}; then
 fi
 
 case $1 in
-"view_aliases")
-  secrets::get_all_aliases | secrets::fzf "View secret aliases"
-  exit
-  ;;
-"view_files")
-  secrets::find --exclude files | secrets::fzf "View secet stored files"
-  exit
-  ;;
-"delete")
-  # Provided file
-  if [[ -n "${secret_path:-}" ]]; then
-    file_secret_path="$(secrets::check_exists "files/$secret_path")"
-    if [[ -z $file_secret_path ]]; then
-      output::error "🗃 Eror 404: File not found"
-      exit 1
+  "view_aliases")
+    secrets::get_all_aliases | secrets::fzf "View secret aliases"
+    exit
+    ;;
+  "view_files")
+    secrets::find --exclude files | secrets::fzf "View secet stored files"
+    exit
+    ;;
+  "delete")
+    # Provided file
+    if [[ -n "${secret_path:-}" ]]; then
+      file_secret_path="$(secrets::check_exists "files/$secret_path")"
+      if [[ -z $file_secret_path ]]; then
+        output::error "🗃 Eror 404: File not found"
+        exit 1
+      fi
+
+      secrets::remove_symlink_by_stored_file "$secret_path"
+    else
+      # Not provided file
+      deleted_items=($(secrets::find --exclude files | secrets::fzf "Select file(s) to be deleted"))
+      for item in "${deleted_items[@]}"; do
+        secrets::remove_symlink_by_stored_file "$item"
+      done
     fi
-
-    secrets::remove_symlink_by_stored_file "$secret_path"
-  else
-    # Not provided file
-    deleted_items=($(secrets::find --exclude files | secrets::fzf "Select file(s) to be deleted"))
-    for item in "${deleted_items[@]}"; do
-      secrets::remove_symlink_by_stored_file "$item"
-    done
-  fi
-  ;;
-"edit")
-  if $by_alias; then
-    files_to_edit=($(secrets::get_all_aliases | secrets::fzf "Edit secrets aliases by alias"))
-  else
-    files_to_edit=($(secrets::find --exclude files | secrets::fzf "Edit secrets stored files alias"))
-  fi
-  
-  output::header "Edit stored file aliases"
-  for item in "${files_to_edit[@]}"; do
-    item_alias=""
-    item_old_alias=""
-    item_stored_file=""
-
+    ;;
+  "edit")
     if $by_alias; then
-      item_alias="$item"
-      item_old_alias="$item"
-      item_stored_file="$(secrets::get_stored_file_by_alias "$item")"
+      files_to_edit=($(secrets::get_all_aliases | secrets::fzf "Edit secrets aliases by alias"))
     else
-      item_alias="$(secrets::get_alias_by_stored_file "$item")"
-      item_old_alias="$item_alias"
-      item_stored_file="$item"
+      files_to_edit=($(secrets::find --exclude files | secrets::fzf "Edit secrets stored files alias"))
     fi
 
-    output::question_default "Choose a new aliases for '$item'" "$item_alias" "item_alias"
+    output::header "Edit stored file aliases"
+    for item in "${files_to_edit[@]}"; do
+      item_alias=""
+      item_old_alias=""
+      item_stored_file=""
 
-    if [[ -n "$item_alias" ]]; then
-      output::answer "Deleting old alias"
-      eval rm -f "$item_old_alias"
-      output::answer "Appending the new alias to secrets file"
-      secrets::append_or_update_value_of_link "$item_alias" "$DOTLY_SECRETS_MODULE_PATH/files/$item_stored_file"
-      output::solution "Updated to '$item_alias' new location"
+      if $by_alias; then
+        item_alias="$item"
+        item_old_alias="$item"
+        item_stored_file="$(secrets::get_stored_file_by_alias "$item")"
+      else
+        item_alias="$(secrets::get_alias_by_stored_file "$item")"
+        item_old_alias="$item_alias"
+        item_stored_file="$item"
+      fi
+
+      output::question_default "Choose a new aliases for '$item'" "$item_alias" "item_alias"
+
+      if [[ -n "$item_alias" ]]; then
+        output::answer "Deleting old alias"
+        eval rm -f "$item_old_alias"
+        output::answer "Appending the new alias to secrets file"
+        secrets::append_or_update_value_of_link "$item_alias" "$DOTLY_SECRETS_MODULE_PATH/files/$item_stored_file"
+        output::solution "Updated to '$item_alias' new location"
+        output::empty_line
+      else
+        output::error "Blank alias could not be aliased. Nothing to do."
+        exit 1
+      fi
+    done
+
+    if $no_sync; then
+      output::write "To apply new alias, needs to execute 'dot secrets apply' manually or"
+      output::write "by sync your secrets 'dot secrets sync', which is the recommended"
+      output::write "way to apply them."
       output::empty_line
+    fi
+    ;;
+  "restore")
+    output::header "Restoring file(s) by aliases"
+    if [[ -n "$secret_alias" ]]; then
+      echo
+      echo "Provided alias: $secret_alias"
+      secrets::relative_path "$secret_alias"
+      echo
+      secrets::restore_by_alias "$(secrets::relative_path "$secret_alias")"
+      output::solution "File '$2' restored ✅"
     else
-      output::error "Blank alias could not be aliased. Nothing to do."
+      secrets_aliases=($(secrets::get_all_aliases | secrets::fzf "Select one or more aliases to restore"))
+      for item in "${secrets_aliases[@]}"; do
+        secrets::restore_by_alias "$item"
+        output::solution "File '$item' restored ✅"
+      done
+    fi
+    exit
+    ;;
+  *)
+    if $prompt && [[ -z "${secrets_subfolder:-}" ]]; then
+      output::question "Relative path inside secrets files subfolder" "secrets_subfolder"
+    fi
+
+    if [[ -z "$item_path" ]]; then
+      "$DOTLY_PATH/bin/dot" secrets file --help
       exit 1
     fi
-  done
 
-  if $no_sync; then
-    output::write "To apply new alias, needs to execute 'dot secrets apply' manually or"
-    output::write "by sync your secrets 'dot secrets sync', which is the recommended"
-    output::write "way to apply them."
-    output::empty_line
-  fi
-  ;;
-"restore")
-  output::header "Restoring file(s) by aliases"
-  if [[ -n "$secret_alias" ]]; then
-    echo
-    echo "Provided alias: $secret_alias"
-    secrets::relative_path "$secret_alias"
-    echo
-    secrets::restore_by_alias "$(secrets::relative_path "$secret_alias")"
-    output::solution "File '$2' restored ✅"
-  else
-    secrets_aliases=($(secrets::get_all_aliases | secrets::fzf "Select one or more aliases to restore"))
-    for item in "${secrets_aliases[@]}"; do
-      secrets::restore_by_alias "$item"
-      output::solution "File '$item' restored ✅"
-    done
-  fi
-  exit
-  ;;
-*)
-  if $prompt && [[ -z "${secrets_subfolder:-}" ]]; then
-    output::question "Relative path inside secrets files subfolder" "secrets_subfolder"
-  fi
-  
-  if [[ -z "$item_path" ]]; then
-    "$DOTLY_PATH/bin/dot" secrets file --help
-    exit 1
-  fi
-
-  secrets::store_file "$item_path" "${secrets_subfolder:-}"
-  ;;
+    secrets::store_file "$item_path" "${secrets_subfolder:-}"
+    ;;
 esac
 
 if ! $no_sync; then
diff --git a/scripts/secrets/init b/scripts/secrets/init
--- a/scripts/secrets/init
+++ b/scripts/secrets/init
@@ -6,7 +6,7 @@
 . "$DOTFILES_PATH/scripts/secrets/src/install_needed_soft_and_vars.sh"
 
 secrets::check_remote_repository_exists() {
-  git ls-remote "$1" >/dev/null 2>&1
+  git ls-remote "$1" > /dev/null 2>&1
 }
 
 red='\033[0;31m'
@@ -28,7 +28,7 @@ normal='\033[0m'
 ##?   init [-h | --help]
 ##?   init [-v | --version]
 ##?   init [-r | --recreate] <git_repository_ssh_url> [<branch>]
-##?   
+##?
 ##?
 ##? Options:
 ##?   -h --help      Show this help
@@ -61,13 +61,16 @@ cd "$DOTFILES_PATH" || {
   exit 1
 }
 
-if ${recreate:-} && [[ -d "$DOTLY_SECRETS_MODULE_PATH" ]] ; then
+if ${recreate:-} && [[ -d "$DOTLY_SECRETS_MODULE_PATH" ]]; then
   output::empty_line
   output::header "WARNING!"
   output::write "You are doing a dangerous action. This will delete all your current secrets."
   output::write "This means that you will delete stored files and vars that could be not "
   output::write "commited to your secrets repository."
-  output::yesno "Are you sure you want to continue" || { output::error "User aborted"; exit 1; }
+  output::yesno "Are you sure you want to continue" || {
+    output::error "User aborted"
+    exit 1
+  }
 
   "$DOTLY_PATH/bin/dot" secrets apply revert
 
@@ -82,7 +85,7 @@ if ${recreate:-} && [[ -d "$DOTLY_SECRETS_MODULE_PATH" ]] ; then
   output::empty_line
 
   output::answer "Your current secrets were moved to:"
-  output::write  "\t$secrets_bk_path"
+  output::write "\t$secrets_bk_path"
   output::empty_line
 
   output::write "${red}Your secrets were not removed, do it by YOUR OWN RISK if you want by executing"
@@ -90,7 +93,7 @@ if ${recreate:-} && [[ -d "$DOTLY_SECRETS_MODULE_PATH" ]] ; then
   output::write "${normal}${red}\trm -rf $secrets_bk_path${normal}"
   output::empty_line
   output::empty_line
-  
+
   output::write "${red}${bold}IS IMPORTANT TO move or remove outside your DOTFILES_PATH because you can append"
   output::write "your secrets to your dotfiles repository now and make them public.${normal}"
   output::empty_line
@@ -99,6 +102,5 @@ fi
 git submodule add -b "${branch:-master}" "$git_repository_ssh_url" "$DOTLY_SECRETS_MODULE_PATH"
 
 "$DOTLY_PATH/bin/dot" secrets apply
-
 
 cd "$start_path" || exit
diff --git a/scripts/ssh/migration/ssh-feature b/scripts/ssh/migration/ssh-feature
--- a/scripts/ssh/migration/ssh-feature
+++ b/scripts/ssh/migration/ssh-feature
@@ -7,7 +7,10 @@ bk_suffix="$(date +%s)"
 
 if [[ -d "$DOTFILES_PATH/ssh" ]]; then
   output::error "This update was applied or you have same file names or directory path."
-  output::yesno "Do you want to perform a backup of your current configuration inside your dotfiles and continue" || { output::error "User aborted"; exit; }
+  output::yesno "Do you want to perform a backup of your current configuration inside your dotfiles and continue" || {
+    output::error "User aborted"
+    exit
+  }
   files::backup_if_file_exists "$DOTFILES_PATH/ssh" "$bk_suffix"
 fi
 
@@ -28,7 +31,6 @@ dotbot::add_or_edit_json_value_to_directive "create" "~/.ssh/control" "$yaml_fil
 dotbot::add_or_edit_json_value_to_directive "link" "~/.ssh/config" "ssh/config" "$yaml_file"
 dotbot::add_or_edit_json_value_to_directive "link" "~/.ssh/config.d" "ssh/config.d" "$yaml_file"
 dotbot::add_or_edit_json_value_to_directive "link" "~/.ssh/config.d-enabled" "ssh/config.d-enabled" "$yaml_file"
-
 
 # TODO Execute symlinks file or user symlinks file
 #"$DOTLY_PATH/bin/dot" symlinks update ssh-feature
